=== rbe/sfm-skb/src/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="skb">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" name="job">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="1" name="dept">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="fab" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="datasource">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="url" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" name="input">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="plugin">
                      <xs:complexType>
                        <xs:attribute name="class" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" name="output" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="plugin">
                      <xs:complexType>
                        <xs:attribute name="class" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rbe/sfm-skb/src/config1.xml
<?xml version="1.0" encoding="UTF-8"?>
<skb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\project\FACT\SKB\src\config.xsd">
    <job name="GCH">
        <datasource name="akvd" url="file:///c:/test.xls" />
        <datasource name="ppr" url="file:///c:/test.csv" />
        <input>
            <plugin class="de.sfhms.skb.processor.plugin.AkvdInputPlugin" />
            <plugin class="de.sfhms.skb.processor.plugin.PprInputPlugin" />
        </input>
        <output>
            <plugin class="string" />
        </output>
    </job>
</skb>
